[env:teensy41]
platform       = teensy
board          = teensy41
framework      = arduino
lib_deps       =
    waspinator/AccelStepper @ ^1.64
build_flags    = -std=gnu++17 -O2
monitor_speed  = 115200
monitor_flags  = --echo
upload_protocol = teensy-cli
